import type { Food, MealSlot } from '../types.js';

/** Instacart-compatible line item (name + optional qty/unit). */
export type GroceryLineItem = {
  key: string;
  name: string;
  quantity: number;
  unit: string;
  foodId: string | null;
};

export type PlannedMeal = {
  localDate: string;
  slot: MealSlot;
  foodId: string;
  servings: number;
  foodName: string;
};

export function aggregateGroceryLineItems(
  plans: Array<{ foodId: string; servings: number }>,
  foodById: (id: string) => Food | null,
): GroceryLineItem[] {
  const buckets = new Map<string, GroceryLineItem>();
  for (const plan of plans) {
    const food = foodById(plan.foodId);
    if (!food || plan.servings <= 0) continue;
    if (food.kind === 'custom' && food.ingredients.length > 0) {
      const batchFactor = plan.servings / Math.max(food.makesServings, 1);
      for (const line of food.ingredients) {
        const qty = line.servings * batchFactor;
        if (qty <= 0) continue;
        const child = line.childFoodId ? foodById(line.childFoodId) : null;
        const name = child?.name ?? line.name;
        const key = line.childFoodId ?? `name:${name.toLowerCase()}`;
        mergeLine(buckets, key, name, qty, 'serving', line.childFoodId);
      }
      continue;
    }
    mergeLine(buckets, food.id, food.name, plan.servings, 'serving', food.id);
  }
  return [...buckets.values()].sort((a, b) => a.name.localeCompare(b.name, undefined, { sensitivity: 'base' }));
}

export function formatGroceryMarkdown(weekStart: string, weekEnd: string, items: GroceryLineItem[], meals: PlannedMeal[]): string {
  const lines: string[] = [
    `# Grocery list`,
    ``,
    `Week of ${weekStart} – ${weekEnd}`,
    ``,
    `## Shopping`,
    ``,
  ];
  if (items.length === 0) {
    lines.push(`- _(nothing planned yet)_`, ``);
  } else {
    for (const item of items) {
      const qty = formatQty(item.quantity);
      lines.push(`- [ ] **${item.name}** — ${qty} ${item.unit}`.trim());
    }
    lines.push(``);
  }
  if (meals.length > 0) {
    lines.push(`## Meals this week`, ``);
    let day = '';
    for (const meal of mealsSorted(meals)) {
      if (meal.localDate !== day) {
        day = meal.localDate;
        lines.push(`### ${day}`, ``);
      }
      lines.push(`- ${meal.slot}: **${meal.foodName}** (${formatQty(meal.servings)} serving${meal.servings === 1 ? '' : 's'})`);
    }
    lines.push(``);
  }
  lines.push(`---`, `_Generated by Nutrition Tracker_`);
  return lines.join('\n');
}

function mealsSorted(meals: PlannedMeal[]): PlannedMeal[] {
  return [...meals].sort((a, b) => a.localDate.localeCompare(b.localDate) || a.slot.localeCompare(b.slot));
}

function mergeLine(
  buckets: Map<string, GroceryLineItem>,
  key: string,
  name: string,
  quantity: number,
  unit: string,
  foodId: string | null,
): void {
  const prev = buckets.get(key);
  if (!prev) {
    buckets.set(key, { key, name, quantity, unit, foodId });
    return;
  }
  prev.quantity += quantity;
}

function formatQty(value: number): string {
  return Number.isInteger(value) ? String(value) : value.toFixed(1);
}
